[[modules-threadpool]]
== Thread Pool

<<<<<<< HEAD
A node holds several thread pools in order to improve how threads are
managed and memory consumption within a node. There are several thread
pools, but the important ones include:

[horizontal]
`index`:: 
    For index/delete operations, defaults to `fixed`, 
    size `# of available processors`. 
    queue_size `200`.

`search`:: 
    For count/search operations, defaults to `fixed`,
    size `3x # of available processors`. 
    queue_size `1000`.

`suggest`::
    For suggest operations, defaults to `fixed`,
    size `# of available processors`.
    queue_size `1000`.

`get`:: 
    For get operations, defaults to `fixed`
    size `# of available processors`.
    queue_size `1000`.

`bulk`::
    For bulk operations, defaults to `fixed`
    size `# of available processors`.
    queue_size `50`.

`percolate`::
    For percolate operations, defaults to `fixed`
    size `# of available processors`.
    queue_size `1000`.

`snapshot`::
    For snapshot/restore operations, defaults to `scaling`
    keep-alive `5m`,
    size `(# of available processors)/2`.

`snapshot_data`::
    For snapshot/restore operations on data files, defaults to `scaling`
    with a `5m` keep-alive,
    size `5`.

`warmer`::
    For segment warm-up operations, defaults to `scaling`
    with a `5m` keep-alive. 

`refresh`:: 
    For refresh operations, defaults to `scaling`
    with a `5m` keep-alive.

Changing a specific thread pool can be done by setting its type and
specific type parameters, for example, changing the `index` thread pool
to have more threads:
=======
A node holds several thread pools in order to improve how threads memory consumption
are managed within a node. Many of these pools also have queues associated with them,
which allow pending requests to be held instead
of discarded.


There are several thread pools, but the important ones include:

`generic`::
    For generic operations (e.g., background node discovery).
    Thread pool type is `cached`.

`index`::
    For index/delete operations. Thread pool type is `fixed`
    with a size of `# of available processors`,
    queue_size of `200`.

`search`::
    For count/search operations. Thread pool type is `fixed`
    with a size of `int((# of available_processors * 3) / 2) + 1`,
    queue_size of `1000`.

`suggest`::
    For suggest operations. Thread pool type is `fixed`
    with a size of `# of available processors`,
    queue_size of `1000`.

`get`::
    For get operations. Thread pool type is `fixed`
    with a size of `# of available processors`,
    queue_size of `1000`.

`bulk`::
    For bulk operations. Thread pool type is `fixed`
    with a size of `# of available processors`,
    queue_size of `50`.

`percolate`::
    For percolate operations. Thread pool type is `fixed`
    with a size of `# of available processors`,
    queue_size of `1000`.

`snapshot`::
    For snapshot/restore operations. Thread pool type is `scaling` with a
    keep-alive of `5m` and a size of `min(5, (# of available processors)/2)`.

`warmer`::
    For segment warm-up operations. Thread pool type is `scaling` with a
    keep-alive of `5m` and a size of `min(5, (# of available processors)/2)`.

`refresh`::
    For refresh operations. Thread pool type is `scaling` with a
    keep-alive of `5m` and a size of `min(10, (# of available processors)/2)`.

`listener`::
    Mainly for java client executing of action when listener threaded is set to true.
    Thread pool type is `scaling` with a default size of `min(10, (# of available processors)/2)`.

Changing a specific thread pool can be done by setting its type-specific parameters; for example, changing the `index`
thread pool to have more threads:
>>>>>>> v2.1.1

[source,js]
--------------------------------------------------
threadpool:
    index:
<<<<<<< HEAD
        type: fixed
        size: 30
--------------------------------------------------

NOTE: you can update threadpool settings live using
      <<cluster-update-settings>>.

=======
        size: 30
--------------------------------------------------

NOTE: you can update thread pool settings dynamically using <<cluster-update-settings>>.
>>>>>>> v2.1.1

[float]
[[types]]
=== Thread pool types

<<<<<<< HEAD
The following are the types of thread pools that can be used and their
respective parameters:

[float]
==== `cache`

The `cache` thread pool is an unbounded thread pool that will spawn a
thread if there are pending requests. Here is an example of how to set
it:
=======
The following are the types of thread pools and their respective parameters:

[float]
==== `cached`

The `cached` thread pool is an unbounded thread pool that will spawn a
thread if there are pending requests. This thread pool is used to
prevent requests submitted to this pool from blocking or being
rejected. Unused threads in this thread pool will be terminated after
a keep alive expires (defaults to five minutes). The `cached` thread
pool is reserved for the <<modules-threadpool,`generic`>> thread pool.

The `keep_alive` parameter determines how long a thread should be kept
around in the thread pool without doing any work.
>>>>>>> v2.1.1

[source,js]
--------------------------------------------------
threadpool:
<<<<<<< HEAD
    index:
        type: cached
=======
    generic:
        keep_alive: 2m
>>>>>>> v2.1.1
--------------------------------------------------

[float]
==== `fixed`

The `fixed` thread pool holds a fixed size of threads to handle the
requests with a queue (optionally bounded) for pending requests that
have no threads to service them.

The `size` parameter controls the number of threads, and defaults to the
number of cores times 5.

The `queue_size` allows to control the size of the queue of pending
requests that have no threads to execute them. By default, it is set to
`-1` which means its unbounded. When a request comes in and the queue is
full, it will abort the request.

[source,js]
--------------------------------------------------
threadpool:
    index:
<<<<<<< HEAD
        type: fixed
=======
>>>>>>> v2.1.1
        size: 30
        queue_size: 1000
--------------------------------------------------

[float]
<<<<<<< HEAD
=======
==== `scaling`

The `scaling` thread pool holds a dynamic number of threads. This number is
proportional to the workload and varies between 1 and the value of the
`size` parameter.

The `keep_alive` parameter determines how long a thread should be kept
around in the thread pool without it doing any work.

[source,js]
--------------------------------------------------
threadpool:
    warmer:
        size: 8
        keep_alive: 2m
--------------------------------------------------

[float]
>>>>>>> v2.1.1
[[processors]]
=== Processors setting
The number of processors is automatically detected, and the thread pool
settings are automatically set based on it. Sometimes, the number of processors
are wrongly detected, in such cases, the number of processors can be
explicitly set using the `processors` setting.

In order to check the number of processors detected, use the nodes info
API with the `os` flag.
